### ISSUE TITLE
Unify content area and their elements styles.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#37]
Our approach to templates dictates that each editable content area elements should have the same styling.
Each `{% content %}`, `{% contentblock %}`, `{% editable article.excerpt %}` and `{% editable article.body %}` must be wrapped into a element with class named `content-area` (`content-formatted` or `formatted` in older templates).

All content elements (e.g. `<h1>`, `<h2>`, `<p>`, ....) must get their styles from this parent class. For example:

```css
.content-area, .content-area p { font-size: 16px; } /* ".content-area" to style plaintext in it  */

.content-area h1 { font-size: 20px; }

.content-area h2 { font-size: 18px; }

.content-area p { color: red; }
```

In that way all content areas have the same basic styles. These styles should so be set so that the content in main content area (in "Common page" layout) looks normal. If any `{% content %}` area needs specific styling it should be overwritten. For example:

```scss
.content-area h1 {
  font-size: 20px;

  .site-header & {
    font-size: 30px;
  }
}
```

Currently each content area have their own styling for the same elements:

![nov-15-2016 15-45-06](https://cloud.githubusercontent.com/assets/3191867/20308357/29ad4ac2-ab4c-11e6-9a48-9ac164cdb574.gif)

## Some main tasks to solve this issue:

- [x] Refactor SCSS so all items that can be edited using wysihtml editor gets their styles from **sources/stylesheets/content/_text.scss**

---

- [x] Don't apply large font sizes as default for specific areas. All content areas plain texts should have the same font size. The desired styling should come from the specific element.

For example: "Front page" content are plain text looks like this:

![screenshot 2016-11-15 15 59 42](https://cloud.githubusercontent.com/assets/3191867/20308435/8fb427fa-ab4c-11e6-9cce-6a11b3882342.png)

But it should look like common page's plain text:

![screenshot 2016-11-15 16 00 57](https://cloud.githubusercontent.com/assets/3191867/20308461/b547a884-ab4c-11e6-8810-9ed3fbecbc75.png)

To get the same style as in design file, a user should set this text as `<h1>` which has specific styles for this content area (as described above).

On signup we can generate a `<h1>` (or any other) tag for the default content so the content looks as designed.

---

- [x] Don't set `text-align: center;` on content area container level. If any of the heading elements are aligned center in template then add it into their CSS. Plain text shoult be aligned to left in all `.content area`-s.

Example:

![screenshot 2016-11-15 16 06 54](https://cloud.githubusercontent.com/assets/3191867/20308644/92fb5284-ab4d-11e6-91e5-db362320f2a6.png)
