### ISSUE TITLE
pre { } selector is defined twice in "sources/stylesheets/content/_text.scss"

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#70]
There's no need to declare it twice.
Instead of doing that:

```css
  pre {
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    padding: 10px;

    code {
      display: inline;
      padding: 0;
      white-space: pre;
      line-height: inherit;
      background-color: transparent;
    }
  }

  code {
    display: inline-block;
    vertical-align: middle;
    overflow: auto;
    box-sizing: border-box;
    max-width: 100%;
  }

  pre {
    .site-header &,
    .site-footer & {
      text-align: left;
      background-color: rgba(244, 244, 244, 1);
      text-transform: none;
    }
  }
```

do that:

```css
  pre {
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    padding: 10px;

    .site-header &,
    .site-footer & {
      text-align: left;
      background-color: rgba(244, 244, 244, 1);
      text-transform: none;
    }

    code {
      display: inline;
      padding: 0;
      white-space: pre;
      line-height: inherit;
      background-color: transparent;
    }
  }

  code {
    display: inline-block;
    vertical-align: middle;
    overflow: auto;
    box-sizing: border-box;
    max-width: 100%;
  }
```
