### ISSUE TITLE
Use SCSS nesting to write CSS rules.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#81]
(Pull request: #100)

For example in **https://github.com/Voog/design-longyearbyen/blob/master/sources/stylesheets/general/_menus.scss#L281-L292** instead of

writing native CSS like this:

```scss
#mobile-menu .mobile-menu-close:before,
#mobile-menu .mobile-menu-close:after {
  position: absolute;
  top: 19px;
  left: 12px;
  display: block;
  width: 20px;
  height: 3px;
  content: '';
  background: white;
  border-radius: 3px;
}
```

...use SCSS nesting:

```scss
#mobile-menu {
  .mobile-menu-close {
    &::before,
    &::after {
      position: absolute;
      top: 19px;
      left: 12px;
      display: block;
      width: 20px;
      height: 3px;
      content: '';
      background: white;
      border-radius: 3px;
    }
  }
}
```
